### ISSUE TITLE
Style issue in .document-footer-meta

### ISSUE THREAD

**Issue by tomtaylor** [alphagov/whitehall#1839]
On [this page](https://www.gov.uk/government/consultations/social-value-act-review), it would be good to have some more spacing between the `dd` elements in `#whitehall-wrapper .document-footer-meta .primary-metadata dd`, so it's a bit more readable.

**Comment by dsingleton** [comment]
The fix in #1942 will get deployed early next week. 

Sorry for the delay. It got fixed in the [standardised component](http://govuk-component-guide.herokuapp.com/component/document_footer), but was overlooked here
