### ISSUE TITLE
publications#show doesn't support JSON

### ISSUE THREAD

**Issue by billinghamj** [alphagov/whitehall#2074]
Could you add a JSON output for publications?

Example resource:

https://www.gov.uk/government/publications/msn-1853-m-boatmasters-qualifications-crew-and-hours-of-work

Proposed URL:

https://www.gov.uk/government/publications/msn-1853-m-boatmasters-qualifications-crew-and-hours-of-work.json

Currently returns a 404

Expected JSON document

Relevant code: https://github.com/alphagov/whitehall/blob/master/app/controllers/publications_controller.rb#L26

**Comment by benilovj** [comment]
Hi James,

If it helps, there's an (unsupported) API; here it is for your example:

https://www.gov.uk/api/government/publications/msn-1853-m-boatmasters-qualifications-crew-and-hours-of-work.json

However this only contains some metadata, not the publication content.

**Comment by billinghamj** [comment]
Oh weird. I didn't know you still had the routes where the path starts with /api/

We've ended up using the Atom feed, as that does include the content (which is the key stuff we need). It would still be good to add JSON feeds for content though.

**Comment by elliotcm** [comment]
@billinghamj We have those, looking like this: https://www.gov.uk/api/content/government/publications/msn-1853-m-boatmasters-qualifications-crew-and-hours-of-work

Also unsupported, currently.

**Comment by billinghamj** [comment]
@elliotcm Doesn't include the publication content though - which is the key thing. Currently the only way to get content is to use a slow & primitive ATOM/RSS feed.

**Comment by elliotcm** [comment]
Ah yes, that part of the site hasn't been fully migrated over to that API yet.  It will fill out eventually.
