### ISSUE TITLE
Spaces before headings in HTML publications cause misalignment

### ISSUE THREAD

**Issue by alextea** [alphagov/whitehall#2408]
Examples from: https://www.gov.uk/government/publications/let-property-campaign-your-guide-to-making-a-disclosure/let-property-campaign-your-guide-to-making-a-disclosure

Example govspeak:
`###1.5 What’s in it for me?`

Example HTML output:
`<h3 id="whats-in-it-for-me">
<span class="number">1.5 </span> What’s in it for me?</h3>`

Example screenshot:
![screen shot 2015-12-08 at 12 10 10](https://cloud.githubusercontent.com/assets/523014/11655335/d1bd7ba8-9da4-11e5-8905-8dfad2571d6c.png)

The space after the span means the title is misaligned with the text below.

Removing the space will correct the alignment:

![screen shot 2015-12-08 at 12 10 23](https://cloud.githubusercontent.com/assets/523014/11655495/1fef9b8e-9da6-11e5-8e82-fc874a1da425.png)

**Comment by alextea** [comment]
This could be an issue in @alphagov/govspeak – I'm not clear on which app outputs the HTML

**Comment by jamiecobbett** [comment]
I think the problem comes from here: https://github.com/alphagov/whitehall/blob/master/app/helpers/govspeak_helper.rb#L45

**Comment by elliotcm** [comment]
Do we have a ticket to fix this?

**Comment by benlovell** [comment]
We're in the process of migrating these, so perhaps this could stay on hold until we're done?

**Comment by boffbowsh** [comment]
This is fixed in government-frontend
