### ISSUE TITLE
SSL issue with https://assets-origin.integration.publishing.service.gov.uk

### ISSUE THREAD

**Issue by eeeschwartz** [alphagov/whitehall#2440]
Hello from a fellow gov content/technology enthusiast!

I'm dying to explore the Whitehall contributor experience given all the user research you've undoubtedly done. It may well change my life.

[Following along](https://github.com/alphagov/whitehall#assets) to set up a local instance, I'm running into an SSL error when connecting to https://assets-origin.integration.publishing.service.gov.uk.

Is there another URL that would work better? Any thoughts greatly appreciated.

**Comment by jamiecobbett** [comment]
Hi @eeeschwartz, can you try: https://assets.digital.cabinet-office.gov.uk/

**Comment by elliotcm** [comment]
Closing on the assumption this has sorted you out, @eeeschwartz.

**Comment by eeeschwartz** [comment]
Thanks for the help. I was able to get it sorted out with https://assets.digital.cabinet-office.gov.uk/
