### ISSUE TITLE
Policies route removed, but link is still there

### ISSUE THREAD

**Issue by Vanuan** [alphagov/whitehall#2558]
It looks like that policies route was removed in 006aa80b7c58f0e5dbfa2729d7963fea054fb42f.
But it is still displayed in the header:

![screenshot from 2016-04-15 10 08 50](https://cloud.githubusercontent.com/assets/361985/14553925/2a1e1fe8-02f2-11e6-848e-aaffc6212c1b.png)

Leading to 404.

**Comment by boffbowsh** [comment]
That's correct, Policies are now rendered by a different app. They still exist on GOV.UK: https://www.gov.uk/government/policies

**Comment by Vanuan** [comment]
Got it. Could you direct me to what repo is it?

**Comment by boffbowsh** [comment]
Sure: https://github.com/alphagov/finder-frontend/.

It pulls a [content item](https://www.gov.uk/api/content/government/policies) from [content-store](https://github.com/alphagov/content-store) which tells it what to render. The content item is added by the [policy-publisher](https://github.com/alphagov/policy-publisher) app. The actual searching is performed by [rummager](https://github.com/alphagov/rummager).
