### ISSUE TITLE
FOI is incorrectly capitalised on publications page

### ISSUE THREAD

**Issue by alexmuller** [alphagov/whitehall#2662]
https://www.gov.uk/government/publications?publication_filter_option=foi-releases

The title is "Publications: foi releases"

**Comment by tijmenb** [comment]
Looks intentional: https://github.com/alphagov/whitehall/pull/1939, perhaps so that it's "Publications: news stories" instead of "Publications: News stories".

**Comment by alexmuller** [comment]
Thanks for digging, I had a feeling it was inadvertently introduced while doing something like that :)
