### ISSUE TITLE
Assets renamed in next release of govuk_frontend_toolkit

### ISSUE THREAD

**Issue by gemmaleigh** [alphagov/whitehall#2793]
This repo uses the accordion icon from the govuk_frontend_toolkit.

The spelling of this icon has been corrected in the next release of the frontend toolkit - version 5.0.0.

Please be aware that when this repo is updated to use the latest version of the frontend toolkit, the name of this asset will have changed and line 25 in the `_historic-people-list.scss` will need to be updated accordingly.

https://github.com/alphagov/whitehall/blob/19cd7d72de32454d532c195f35b027fa1b3ba6ac/app/assets/stylesheets/frontend/helpers/_historic-people-list.scss#L25

**Comment by nickcolley** [comment]
Closed with https://github.com/alphagov/whitehall/pull/2839 thanks @gemmaleigh @fofr

**Comment by fofr** [comment]
It was using its own local version. I updated anyway.
