### ISSUE TITLE
How Government Work 'Circles' render oddly and are not accessible

### ISSUE THREAD

**Issue by nickcolley** [alphagov/whitehall#2850]
Issue found while visiting the Scottish Government's Device Lab

![image](https://cloud.githubusercontent.com/assets/2445413/20501850/75c3eeb6-b033-11e6-9ee7-7887636eb3f6.png)

Also see this video for accessibility concerns
https://www.youtube.com/watch?v=CULhzDFFDoE

https://www.gov.uk/government/how-government-works

**Comment by kr8n3r** [comment]
![Screenshot_20200302-172914](https://user-images.githubusercontent.com/3758555/75701294-6c0a5180-5cab-11ea-97e8-dfda0a375a96.png)
closing this, as this design has been removed
