### ISSUE TITLE
Translated pages are unpronounceable by assistive tech

### ISSUE THREAD

**Issue by nickcolley** [alphagov/whitehall#2864]
Issue found while visiting the Scottish Government's Device Lab

When testing with VoiceOver on iPad I found that these pages can not be accessed at all.

https://www.gov.uk/government/world/saudi-arabia

https://drive.google.com/file/d/0B-GzTJBVVSNzcnpQa2d6Nk5fVjA/view?usp=sharing

I think this could be solved by making sure we're setting the right `lang` attribute  https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang

I've tested the BBC Arabic site and VoiceOver was able to read that fine.

**Comment by robinwhittleton** [comment]
Link to the `ar` version should have `lang="ar"` and `hreflang="ar"`. The `ar` page should have `<main lang="ar">` with appropriate `lang="en"` sections.

**Comment by rubenarakelyan** [comment]
https://github.com/alphagov/whitehall/pull/2895 and https://github.com/alphagov/government-frontend/pull/204 need to be built-upon to add the `hreflang` attribute.

**Comment by robinwhittleton** [comment]
I might be wrong about `hreflang` actually as the whole page is still `lang="en"`, it just has alternate language sections. The `lang` Attribute is still needed.

**Comment by rubenarakelyan** [comment]
But if the majority of the content on the page is in another language, is `lang="en"` still right for the `<html>` tag, or should we instead be marking up English where it appears?

**Comment by robinwhittleton** [comment]
Yeah, `<html lang="en">` is correct on GOV.UK. In terms of tree structure, the top level content (i.e. header and footer) is in English, and it’s only when you get into the content that you would need to mark that up as `lang="xx"`. HTML language works on the tree rather than majorities.

**Comment by tijmenb** [comment]
Now tracked https://trello.com/c/O3Dqb6HR/40-fix-screen-reading-for-translated-pages, because it's not a Whitehall-specific issue.
