### ISSUE TITLE
Available languages links need lang attributes

### ISSUE THREAD

**Issue by robinwhittleton** [alphagov/whitehall#2873]
Language links are presented to the user as the name of the language in the language the link points too. For example, https://www.gov.uk/government/organisations/wales-office has a link to ‘Cymraeg’. This language name needs a `lang` attribute on the link so that screen-readers can pronounce it properly. The value of that attribute should be the appropriate language code.

The link can be found at https://github.com/alphagov/whitehall/blob/19cd7d72de32454d532c195f35b027fa1b3ba6ac/app/views/shared/_available_languages.html.erb#L9

**Comment by fofr** [comment]
A corresponding fix should also be added to government-frontend:
https://github.com/alphagov/government-frontend/blob/master/app/views/shared/_available_languages.html.erb
