### ISSUE TITLE
Pages written in RTL languages have odd rendering of LTR text

### ISSUE THREAD

**Issue by rubenarakelyan** [alphagov/whitehall#2903]
On pages where the majority text is right-to-left (for example, https://www.gov.uk/government/world/saudi-arabia.ar), whitehall sets the `text-direction: rtl` CSS rule for the whole page. However, this results in embedded English text being rendered oddly to comply with right-to-left rules.

![screen shot 2016-12-05 at 13 33 24](https://cloud.githubusercontent.com/assets/444232/20886800/b3e5ff4c-baef-11e6-98f3-0548401460c2.png)

See in particular the positioning of brackets and full stops.

https://github.com/alphagov/whitehall/issues/2864 should also fix this as long as all language sections are marked up appropriately.

**Comment by suzannehamilton** [comment]
This also breaks the pagination text, for example on https://www.gov.uk/government/announcements.ar?page=2:

<img width="657" alt="screen shot 2017-08-21 at 14 05 12" src="https://user-images.githubusercontent.com/754712/29524374-90689818-8687-11e7-8108-63306144c573.png">

Untranslated text like "of 45 1" should read "1 of 45" as it does on left-to-right pages like https://www.gov.uk/government/announcements?page=2

<img width="654" alt="screen shot 2017-08-21 at 14 05 17" src="https://user-images.githubusercontent.com/754712/29524470-d0457f1e-8687-11e7-9533-52bd82b57ae7.png">

**Comment by fofr** [comment]
Is there an easy way to distinguish which parts of the page are in English and which aren't?

**Comment by andysellick** [comment]
Fix for the pagination issue has been done: https://github.com/alphagov/whitehall/pull/3449

**Comment by ChrisBAshton** [comment]
Linked PR above has been merged. A lot has changed since this issue was raised, not least the moving of rendering out of Whitehall and into the frontends. Closing.
