### ISSUE TITLE
‘How government works’ images resize oddly on smaller screens.

### ISSUE THREAD

**Issue by robinwhittleton** [alphagov/whitehall#2933]
![how-government-works](https://cloud.githubusercontent.com/assets/7414/21315060/391a4d00-c5f2-11e6-9735-f2ca55cb08ba.gif)

1. Top image resizes at a different break point to the bottom image
2. Line above the second block of content on desktop appears below the image on mobile

**Comment by rounaksarda** [comment]
I can work on this issue.

**Comment by robinwhittleton** [comment]
Page layout has changed such that this is no longer an issue.
