### ISSUE TITLE
Additional resources needed for setting up a local development copy

### ISSUE THREAD

**Issue by duncanjbrown** [alphagov/whitehall#2966]
I'm not a member of GDS, just an interested citizen.

I cloned this repo and followed the [Detailed Setup Guide](https://github.com/alphagov/whitehall/blob/master/docs/detailed_setup_guide.md). `bundle install`  and `rake db:setup` went fine.

Some errors: 

- Visiting `/`, though it's not recommended, results in an error: `Slimmer::CouldNotRetrieveTemplate: Unable to fetch: 'core_layout' from 'http://static.dev.gov.uk/templates/core_layout.html.erb' because getaddrinfo: nodename nor servname provided, or not known`
- Visting `/government/admin/publications/new` results in `SocketError: getaddrinfo: nodename nor servname provided, or not known`. 

Is it possible to run the app without these external dependencies?

**Comment by gxrneyme** [comment]
Did you ever manage to resolve this, Duncan? Same issue.
