### ISSUE TITLE
"Coming soon" content items in the past

### ISSUE THREAD

**Issue by fofr** [alphagov/whitehall#3223]
There are 142 content items with the schema_name "Coming soon" which tell users that this content will be published on a date that's in the past.

Example:
https://www.gov.uk/government/case-studies/ww1-australian-vc-recipient-corporal-alexander-stewart-burton

![screen shot 2017-05-13 at 11 03 32](https://cloud.githubusercontent.com/assets/319055/26024570/d2e7644a-37cb-11e7-9b07-f041b1b480b2.png)

## See list of 142
```
all = ContentItem.where(schema_name: 'coming_soon').to_a
y all.select {|c| Date.parse(c.details[:publish_time]) < Date.today }.map {|c| [c._id, c.details[:publish_time]] }
```

cc @gpeng @rubenarakelyan @nickcolley

**Comment by rubenarakelyan** [comment]
I've added this to our support board

**Comment by ChrisBAshton** [comment]
No loner seems to be a thing:

```
ContentItem.where(schema_name: 'coming_soon').to_a
=> []
```
