### ISSUE TITLE
Delete frontend parts for migrated formats

### ISSUE THREAD

**Issue by fofr** [alphagov/whitehall#3241]
Whitehall contains frontend code for formats it no longer renders.

Templates, controllers, tests, javascripts and styles should be removed

Based on https://github.com/alphagov/whitehall/tree/master/app/views, these formats still have frontend code in Whitehall:

* [x] Consultations (https://github.com/alphagov/whitehall/pull/3334)
* [x] Case studies (https://github.com/alphagov/whitehall/pull/3332)
* [ ] Corporate information pages (except worldwide corp info pages)
* [x] Document collections (https://github.com/alphagov/whitehall/pull/3335)
* [x] HTML Attachments (with care to leave in code for rendering CSVs) (https://github.com/alphagov/whitehall/pull/3362 – a lot still present for CSVs though)
* [x] Publications (https://github.com/alphagov/whitehall/pull/3370)

cc @rubenarakelyan @gpeng @nickcolley

**Comment by rubenarakelyan** [comment]
Thanks for this Paul - I'll check to see if we have something on our support list and add it if not.

**Comment by fofr** [comment]
WIP on deleting document collections:
https://github.com/alphagov/whitehall/compare/delete-collections-frontend

**Comment by fofr** [comment]
So close to closing this, looks like just corporate information pages to go?

**Comment by rubenarakelyan** [comment]
Yes, although it's the reverse of your checklist - the worldwide ones are rendered by whitehall, and the other ones are government-frontend.

**Comment by ChrisBAshton** [comment]
Whitehall is no longer split into 'Whitehall Admin' and 'Whitehall Frontend' - we only have the former.
I don't see anything legacy in the `views` folder, so I think we can close this.
