### ISSUE TITLE
Use edition links on case studies

### ISSUE THREAD

**Issue by fofr** [alphagov/whitehall#3333]
When creating a new case study and previewing the draft on the draft stack, the links are not accurately displayed because they are not sent as edition links.

The page doesn't error because of the lack of these links, but the preview is not accurate.

Spotted when working on https://github.com/alphagov/whitehall/pull/3332

cc @gpeng @rubenarakelyan

**Comment by ChrisBAshton** [comment]
Tested - links seem fine now.

<img width="1239" alt="Screenshot 2024-06-17 at 14 22 53" src="https://github.com/alphagov/whitehall/assets/5111927/ee540917-85af-4578-b63e-0ac89791a827">
<img width="1021" alt="Screenshot 2024-06-17 at 14 22 57" src="https://github.com/alphagov/whitehall/assets/5111927/af3daca7-1e54-45dd-a68f-552f77120b81">
