### ISSUE TITLE
Search input renders native styling in iOS

### ISSUE THREAD

**Issue by dashouse** [alphagov/whitehall#3340]
On iOS the search input is styled with it's native styling (rounded corners and drop shadow). It’s not something you’d notice by making the screen smaller, only by testing on the device. 

I believe this is due to the absence of `-webkit-appearance: none;` on the input.

![image1](https://user-images.githubusercontent.com/23356842/28265641-b28a9eba-6ae8-11e7-8bf3-a343ab0cc100.PNG)

**Comment by ChrisBAshton** [comment]
I don't think this is an issue anymore (looking at https://www.gov.uk/world/organisations on iOS) - and in any case it wouldn't be Whitehall where the issue lies now, but one of the frontend repos.
