### ISSUE TITLE
Rail Accident Investigation Branch "Independent Reports" don't appear in generic announcements.atom feed

### ISSUE THREAD

**Issue by Muzer** [alphagov/whitehall#3407]
Safety Digests ("Independent Reports") (which as far as I can tell are just RAIB's new name for Bulletins, which do appear) don't appear in this feed:

https://www.gov.uk/government/announcements.atom?departments[]=rail-accident-investigation-branch

But they do appear in this feed:

https://www.gov.uk/government/organisations/rail-accident-investigation-branch.atom

However, the former feed supports pagination (by adding page=n as a GET parameter), whereas the latter feed appears to be hardcoded to a very small number of entries with no ability to change pages that I can find. Either adding pagination to the latter feed or adding the Safety Digests to the former feed will suffice in sorting this issue in my mind :)

Another (probably unrelated, but I'll moan about it here anyway) irritation is that the PDF attachments don't appear in the embedded content HTML for Safety Digests, but they do for full reports; meaning even if they did appear in the right feed, I'd still need to make additional page loads in order to extract the PDF links, when it used to be perfectly possible to do for both reports and bulletins from the Atom feed directly.

**Comment by rubenarakelyan** [comment]
The first feed you refer to is a feed of news stories and press releases - these indicate progress through reports but they are not the reports themselves. RAIB decides which reports to create news articles for.

The second feed is a feed of everything on RAIB's home page, which includes the most recently-published material. This includes news and well as reports and other publications.

If you are looking for reports only, take a look at https://www.gov.uk/raib-reports and its associated feed. This page lists RAIB reports that can be filtered on a number of areas and then turned into an Atom feed.
