### ISSUE TITLE
Setting and updating custom images for speeches must be easier and documented

### ISSUE THREAD

**Issue by fofr** [alphagov/whitehall#3504]
Custom images shown on speech pages are determined by the image used when featuring the speech (https://github.com/alphagov/whitehall/blob/master/app/presenters/publishing_api/speech_presenter.rb#L120). This is different to the process used for News articles – which uses the first uploaded image in the sidebar.

The process to update the image is more convoluted. At the moment the process would be to un-feature the speech and re-feature it with a new image. Presumably something would also need to trigger a republish so the new image gets picked up.

The feature was originally added after a request came through on 2nd line.

Users do not know:
* why an image is used
* how to update images

Users have tried:
* uploading new images to the document itself to see if they display

Context: https://govuk.zendesk.com/agent/tickets/2484542

**Comment by ChrisBAshton** [comment]
This is captured by https://trello.com/c/rbdWOeDd/12-change-the-lead-image-in-a-speech
