### ISSUE TITLE
Statistics finder - Filters not persistent across tabs

### ISSUE THREAD

**Issue by dashouse** [alphagov/whitehall#3526]
**Steps to recreate**

1. Go to https://www.gov.uk/government/statistics
2. Select filter for Department (or anything)
3. Select "Upcoming"

**Expected result**
Filters persist across tabs

**Actual result**
All filters have been removed

**Comment by kr8n3r** [comment]
statistics finder has since been moved to finder-frontend and the interface no longer has tabs, so closing this
