### ISSUE TITLE
No.10 page should not require / use Adobe Flash

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/whitehall#3632]
As discovered by @joelanman, the No.10 history page appears to require Adobe Flash - with it blocked you get the below warning. It also has non standard navigation.

![image_720](https://user-images.githubusercontent.com/2204224/34206245-a7d53d9e-e57d-11e7-9d04-ab1716d28649.png)

https://github.com/alphagov/whitehall/blob/a41ef2edaec2ce63facb2998d3d62c56252a70fe/app/views/histories/10_downing_street.html.erb#L326

As far as I'm aware, we avoid / don't allow flash on GOV.UK. Hoping this can be escalated.

**Comment by nickcolley** [comment]
Link to page: https://www.gov.uk/government/history/10-downing-street

**Comment by nickcolley** [comment]
Will discuss with the Content Community

**Comment by nickcolley** [comment]
Chatted to Abigail Waraker and they have raised this for their team to look at.

**Comment by fofr** [comment]
A WIP branch with the tour deleted:
https://github.com/alphagov/whitehall/compare/delete-tour

Currently awaiting new copy for page.

Undoes #474
