### ISSUE TITLE
Investigate Psych::BadAlias: Unknown alias: nested_attachment_field_names

### ISSUE THREAD

**Issue by andrewgarner** [alphagov/whitehall#3684]
test/unit/text_direction_test.rb contains a `YAML.load` invocation, it would be [preferable to replace this](http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Security/YAMLLoad) with `YAML.safe_load` however doing so produces the following test failure:

```
TextDirectionTest#test_explicitly_sets_text_direction_for_en.yml:¬
Psych::BadAlias: Unknown alias: nested_attachment_field_names¬
```

The `en.yml` file contains the folowing line which appears to be invalid YAML:

```
nested_attachment_field_names: &nested_attachment_field_names
```

**Comment by ChrisBAshton** [comment]
No longer appears to be a thing - I see no `Psych::BadAlias` occurrences in an entire `bundle exec rake test` run.
