### ISSUE TITLE
Strip trailing whitespace from URL inputs

### ISSUE THREAD

**Issue by fofr** [alphagov/whitehall#3724]
Debt Management Office had 4 broken links:

![screen shot 2018-01-26 at 17 27 04](https://user-images.githubusercontent.com/319055/35452602-fc16ad12-02be-11e8-9a25-8a42df47a7ff.png)

**Comment by JohnLRBrock** [comment]
What model is this? This should be as calling #strip on the strings before they're saved.

**Comment by ChrisBAshton** [comment]
Closing as it's unclear which model this was referring to. It could very well have been fixed in the meantime.
