### ISSUE TITLE
Remove "Closed organisation: " prefix from 'title' in API JSON

### ISSUE THREAD

**Issue by frankieroberto** [alphagov/whitehall#4186]
Hi,

A recent change seems to have resulted in including the prefix "Closed organisation: " within the `title` value of closed organisations in the API, eg see example: https://www.gov.uk/api/organisations/health-protection-agency

This seems redundant as there are separate `govuk_status` and `govuk_closed_status` values which describe the status of the organisation.

(It also slightly breaks my [code](https://github.com/frankieroberto/govuk-government-organisations-autocomplete/blob/master/import-from-gov-uk-api.rb) which consumes the API in order to populate an autocomplete of past and current UK government organisations for an internal service.)\

I'm guessing (from a quick glance at the commit history) that this was an accidental consequence of including this prefix within the model/presenters for use in indexing?

Cheers.

**Comment by sihugh** [comment]
Hi Frankie,

Thanks for raising this.  We've moved our API to be generated from search and this crept in.  I've raised a PR to resolve this.

Simon
