### ISSUE TITLE
XML files display odd behaviour

### ISSUE THREAD

**Issue by edent** [alphagov/whitehall#4266]
BEIS have uploaded an XML file to https://www.gov.uk/government/statistical-data-sets/oil-and-petroleum-products-weekly-statistics (let's ignore *why* for now).

Here's how the site renders the link to it:

![screen shot 2018-08-07 at 10 19 39](https://user-images.githubusercontent.com/837136/43766844-71b9f688-9a2b-11e8-86a2-8c078659d55a.png)

Because the MIME type is not recognised, the metadata is displayed as 

> , 361KB

That is `space comma space filesize`.

* Would it be suitable to add a `HUMANIZED_CONTENT_TYPE` in https://github.com/alphagov/whitehall/blob/master/app/helpers/document_helper.rb ?
* If not, can the display logic be changed to only show the filesize, not the comma, when there's no recognised type?

**Comment by deborahchua** [comment]
@edent this is now fixed live 🎉

**Comment by edent** [comment]
Sweet! Thanks.
