### ISSUE TITLE
Use of aria-live inconsistent across www.gov.uk search results

### ISSUE THREAD

**Issue by tombye** [alphagov/whitehall#4383]
Pages that display search results with filters in a left-hand column do not identify the summary information consistently to assistive tech'.

## Overview

When JS is enabled, the search results on these pages are updated by AJAX.

The change in the page content needs to be announced to users of assistive tech'. It's normally done by making the results summary paragraph a live region by adding the `aria-live` attribute.

On the pages of this type owned by whitehall, `aria-live` is set on the search results, not the summary.

## What needs to be done

`aria-live` needs to be set on the results summary paragraph, not the results.

It's value is different for the pages in this repo compared to those owned by [finder-frontend](https://github.com/alphagov/finder-frontend). We should decide on one value for it and make it the same everywhere.

Note: work done on this a while ago was documented in [this excellent blog post](https://gdstechnology.blog.gov.uk/2014/08/14/improving-accessibility-on-gov-uk-search/).

## Pages owned by whitehall

The pages I've found of this type (there may be others) are:

1. https://www.gov.uk/government/publications
2. https://www.gov.uk/government/consultations
3. https://www.gov.uk/government/statistics
4. https://www.gov.uk/government/announcements
5. https://www.gov.uk/government/policies
6. https://www.gov.uk/search

1-4 are owned by this app. I've raised [another issue for this on 5 & 6](https://github.com/alphagov/finder-frontend/issues/612).

**Comment by selfthinker** [comment]
I've left some comments on the linked issue: https://github.com/alphagov/finder-frontend/issues/612#issuecomment-490861983

**Comment by ChrisBAshton** [comment]
NB, the only link of the 6 above that is still on Whitehall is number 3:

https://www.gov.uk/government/statistics

Not sure if/when this will be moved over to finder-frontend like the others, nor who has the answer to that question, but hopefully it will soon and then we can fix the usability issues in one place.

**Comment by tombye** [comment]
As with [the other issue](https://github.com/alphagov/finder-frontend/issues/612) these now all share the same implementation and any issues raised with it are fixed. Nice work! 👍
