### ISSUE TITLE
Long URls don't wrap - causes layout issues on mobil

### ISSUE THREAD

**Issue by edent** [alphagov/whitehall#5596]
Spotted on Chrome for Android (latest version)
<img src="https://user-images.githubusercontent.com/837136/81692239-03331880-9456-11ea-8c8b-76f557759a36.jpg" width="200" />

Also affects Chrome Desktop.

Firefox mobile works better, but has some problems with long strings of text in a URl.

<img src="https://user-images.githubusercontent.com/837136/81692505-658c1900-9456-11ea-8a55-129673678974.jpg" width="200" />

I think either `<a>` elements, or the whole page, needs some [`word-break`](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break) CSS love.

**Comment by cbaines** [comment]
Thanks for the report @edent . Do you happen to have the URL for this page?

**Comment by edent** [comment]
That would probably have helped!
https://www.gov.uk/government/publications/our-plan-to-rebuild-the-uk-governments-covid-19-recovery-strategy/our-plan-to-rebuild-the-uk-governments-covid-19-recovery-strategy

**Comment by edent** [comment]
This appears to now be fixed.
