### ISSUE TITLE
Large-sized numbers have strange underlines on /government/get-involved

### ISSUE THREAD

**Issue by injms** [alphagov/whitehall#6137]
On the ["Get involved"](https://www.gov.uk/government/get-involved) page, the underlines on the link partially obscure the smaller text:
![image](https://user-images.githubusercontent.com/1732331/121209749-0542f300-c873-11eb-92f2-da2c6ab75d6c.png)

**Comment by KludgeKML** [comment]
Does this problem still exist? Looks okay to me at the moment.

**Comment by injms** [comment]
Yep, agreed that this is now fixed.

This page is now rendered by government-frontend - and I think this was fixed in https://github.com/alphagov/government-frontend/commit/58e67833214a1d46caabc94c2d3c5c7b4de7b057
