### ISSUE TITLE
Historic appointments could be consolidated further

### ISSUE THREAD

**Issue by maxgds** [alphagov/whitehall#6265]
Past Prime Ministers, Past Foreign Secretaries and Past Chancellors pages are as of https://github.com/alphagov/whitehall/pull/6264 rendered using the same design patterns but they are handled discretely. It would make sense to reuse the same partials for the output, after manipulating the data to make it suitable to feed in.

**Comment by ChrisBAshton** [comment]
No longer a Whitehall thing. Is this on the Web tech debt board @maxgds @leenagupte ?

Closing this issue in the meantime.
