### ISSUE TITLE
Missing Local data - images

### ISSUE THREAD

**Issue by chris-gds** [alphagov/whitehall#6270]
## What 

[While working on this PR](https://github.com/alphagov/whitehall/pull/6264) on pages including [the Past Prime Minster page](https://www.gov.uk/government/history/past-prime-ministers) it was noticed the images are not available on locally 

## Impact

Although not a massive issue (as this image can be replaced with a placeholder) It does mean that local is not an accurate reflection and requires integration deployment in order to view / test with the correct data.   

It has also resulted in additional considerations / changes due to live images being difference dimensions

**Comment by ChrisBAshton** [comment]
Captured as tech debt here: https://trello.com/c/IzsbMbEK/5-we-dont-have-usable-seed-data-in-the-publishing-applications
