### ISSUE TITLE
Missing local data  - World Locations

### ISSUE THREAD

**Issue by chris-gds** [alphagov/whitehall#6276]
## What

Inaccurate or missing data on local - revealed working [on this PR](https://github.com/alphagov/whitehall/pull/6147)

- announcements
- latest
- images

## How to replicate:

Live / Integration > Local

[gov.uk/world/france/news](www.gov.uk/world/france/news)

![Screenshot 2021-09-10 at 13 01 27](https://user-images.githubusercontent.com/71266765/132850495-19181275-f4df-429a-b940-1ecad1e3d8dd.png)

![Screenshot 2021-09-10 at 13 01 17](https://user-images.githubusercontent.com/71266765/132850497-7a3d0644-d8b1-42ed-bd46-c534a89e16fb.png)

![Screenshot 2021-09-10 at 13 01 05](https://user-images.githubusercontent.com/71266765/132850501-ca97dec1-2ae6-43f5-9180-c11dda3ab947.png)

**Comment by owenatgov** [comment]
Why did this stop the PR from getting merged in when I initially approved it over a month ago?

**Comment by chris-gds** [comment]
Mainly as this page wasn't able to be updated in insolation / reflective of the ways tickets were split up.  There were multiple files with `/app/views/shared` that required updating across many pages and templates in parallel.

**Comment by ChrisBAshton** [comment]
This is captured as a tech debt card: https://trello.com/c/IzsbMbEK/5-we-dont-have-usable-seed-data-in-the-publishing-applications
