### ISSUE TITLE
Announcements page - content

### ISSUE THREAD

**Issue by chris-gds** [alphagov/whitehall#6306]
## What

The Announcements page doesn't behave as expected
https://www.gov.uk/government/announcements.ka?world_locations%5B%5D=bahamas

## To Replicate 

If you navigate to the page in English and attempt to change country via the `select` there is no data presented. 

However if you alter the URL to something like `fr` eg (https://www.gov.uk/government/announcements.fr?world_locations%5B%5D=all). More Content is present, however this is seemingly the same Content that should be present in English.

## Expected Behaviour 

More of the Announcement Content is present while navigating in English.

**Comment by ChrisBAshton** [comment]
The announcements page no longer seems to exist. Closing.
