### ISSUE TITLE
Remove obsolete PDF thumbnail generation feature and Ghostscript dependency

### ISSUE THREAD

**Issue by sengi** [alphagov/whitehall#7480]
Whitehall currently uses Ghostscript to generate thumbnail icons for PDF attachments.

~~It's not clear whether this is even a useful feature (since most document cover pages look very similar and the thumbnail is too small for text to be readable), but if we want to keep generating these thumbnails then it's worth considering switching from Ghostscript to pdf.js to reduce the attack surface.~~

Ghostscript is 70+ MB of old code, mostly written in C ~~, whereas pdf.js is way smaller and designed for security from the beginning.~~

See Keith's comment below. We just need to delete the thumbnail code and remove Ghostscript.

**Comment by KludgeKML** [comment]
Related Issue: https://github.com/alphagov/whitehall/issues/9142

The frontend rendering apps now handle attachments directly, and we just use generic icons. It should now be safe for the whitehall team can remove pre-rendering of attachments and the thumbnail rendering code, and get rid of Ghostscript.

**Comment by ChrisBAshton** [comment]
Thanks both - I've raised https://trello.com/c/vjSowrs7/237-remove-thumbnail-generation-from-whitehall.
