### ISSUE TITLE
'Back' link doesn't work in organisation pages, Promotional Feature

### ISSUE THREAD

**Issue by andysellick** [alphagov/whitehall#9047]
The 'Back' link when [editing a Promotional Feature](https://whitehall-admin.staging.publishing.service.gov.uk/government/admin/organisations/prime-ministers-office-10-downing-street/promotional_features/51) on the Promotional Features section of an organisation page isn't working. I'm experiencing this on the No.10 page. The link is pointing to `/government/admin/organisations/prime-ministers-office-10-downing-street/promotional_features/admin%20Prime%20Minister's%20Office,%2010%20Downing%20Street%20PromotionalFeature` but should point to `/government/admin/organisations/prime-ministers-office-10-downing-street/promotional_features`.

Have experienced this on staging and integration. It's quite a blocker because to get back to editing the main part of the organisation page you have to navigate to it from scratch (More -> Departments, find the right one).

![Screenshot 2024-05-16 at 09 04 24](https://github.com/alphagov/whitehall/assets/861310/e983349c-4bb7-4630-a4e3-7738349d54c9)

**Comment by rimshach2** [comment]
@andysellick if no one is working on this, can I take up this issue?

**Comment by ChrisBAshton** [comment]
Should be fixed by #9230.
